# Generated by Django 4.1.3 on 2022-12-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="commentor",
            field=models.CharField(max_length=50),
        ),
    ]
