# Generated by Django 4.1.3 on 2022-12-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_article_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="comment",
        ),
        migrations.AddField(
            model_name="article",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.comment",
            ),
        ),
    ]
