# Generated by Django 4.1.3 on 2022-12-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_article_comment_article_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="comment",
        ),
        migrations.AddField(
            model_name="article",
            name="comment",
            field=models.ManyToManyField(blank=True, to="main.comment"),
        ),
    ]
