# Generated by Django 4.1.3 on 2022-12-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_comment_commentor"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="article_img"),
        ),
    ]
