# Generated by Django 4.1.3 on 2023-01-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_article_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="profile_pics"),
        ),
    ]
