# Generated by Django 4.1.3 on 2023-01-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_profile_about_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.jpg', max_length=250, upload_to='profile_pics'),
        ),
    ]
